import type { ComponentType } from 'react';

export type FeatureTopic =
  | 'typescript'
  | 'react-19'
  | 'hooks'
  | 'component-patterns'
  | 'state-management'
  | 'data-fetching'
  | 'forms'
  | 'routing'
  | 'performance'
  | 'error-handling'
  | 'testing'
  | 'accessibility';

export type FeatureStatus = 'planned' | 'done';

export interface FeatureEntry {
  /** stable kebab-case id, also used as the route slug */
  id: string;
  title: string;
  topic: FeatureTopic;
  /** short one-liner shown on the index card */
  description: string;
  /** why it matters / interview overlap, shown expanded on the index card */
  interviewNotes: string;
  status: FeatureStatus;
  /** route path relative to the sandbox root, e.g. "/hooks/use-reducer" */
  path: string;
  /** present only once status is 'done' — kept lazy so each demo is its own chunk */
  component?: () => Promise<{ default: ComponentType }>;
}

export const topicLabels: Record<FeatureTopic, string> = {
  typescript: 'TypeScript',
  'react-19': 'React 19',
  hooks: 'Hooks',
  'component-patterns': 'Component Patterns',
  'state-management': 'State Management',
  'data-fetching': 'Data Fetching',
  forms: 'Forms',
  routing: 'Routing',
  performance: 'Performance',
  'error-handling': 'Error Handling',
  testing: 'Testing',
  accessibility: 'Accessibility',
};

/** Order the topic sections appear in on the sandbox home page. */
export const topicOrder: FeatureTopic[] = [
  'typescript',
  'react-19',
  'hooks',
  'component-patterns',
  'state-management',
  'data-fetching',
  'forms',
  'routing',
  'performance',
  'error-handling',
  'testing',
  'accessibility',
];

export const featureRegistry: FeatureEntry[] = [
  // --- TypeScript ---
  {
    id: 'generics',
    title: 'Generics',
    topic: 'typescript',
    description: 'Reusable, type-safe functions and components via generic type parameters.',
    interviewNotes: 'Classic "write a generic useLocalStorage/useFetch hook" ask.',
    status: 'planned',
    path: '/typescript/generics',
  },
  {
    id: 'utility-types',
    title: 'Utility Types',
    topic: 'typescript',
    description: 'Partial, Pick, Omit, Record, ReturnType and friends applied to real props/state shapes.',
    interviewNotes: 'Tests whether you reach for built-ins instead of hand-rolling duplicate types.',
    status: 'planned',
    path: '/typescript/utility-types',
  },
  {
    id: 'discriminated-unions',
    title: 'Discriminated Unions',
    topic: 'typescript',
    description: 'Modeling state (loading/error/success) as a tagged union instead of loose booleans.',
    interviewNotes: 'Directly maps to "how do you model async state" and exhaustiveness-check questions.',
    status: 'planned',
    path: '/typescript/discriminated-unions',
  },
  {
    id: 'satisfies',
    title: 'satisfies Operator',
    topic: 'typescript',
    description: 'Validating an object against a type without widening or losing literal inference.',
    interviewNotes: 'Newer TS feature interviewers use to check if your knowledge is current.',
    status: 'planned',
    path: '/typescript/satisfies',
  },
  {
    id: 'template-literal-types',
    title: 'Template Literal Types',
    topic: 'typescript',
    description: 'Building string-pattern types, e.g. typed event names or CSS-variable keys.',
    interviewNotes: 'Comes up in typed routing/i18n-key/design-token discussions.',
    status: 'planned',
    path: '/typescript/template-literal-types',
  },
  {
    id: 'conditional-mapped-types',
    title: 'Conditional & Mapped Types',
    topic: 'typescript',
    description: 'Deriving new types from existing ones with `extends`/`infer` and key remapping.',
    interviewNotes: '"How would you type a deep Partial/Readonly" is a common senior-level probe.',
    status: 'planned',
    path: '/typescript/conditional-mapped-types',
  },
  {
    id: 'type-narrowing-guards',
    title: 'Type Narrowing & Guards',
    topic: 'typescript',
    description: 'Custom type predicates (`is`), `in`/`instanceof` checks, exhaustive switch narrowing.',
    interviewNotes: 'Shows up any time union types meet runtime branching logic.',
    status: 'planned',
    path: '/typescript/type-narrowing-guards',
  },
  {
    id: 'as-const',
    title: 'as const',
    topic: 'typescript',
    description: 'Locking literal types and readonly-ness for config objects and enums-as-arrays.',
    interviewNotes: 'Common alternative to TS enums; interviewers ask why you would prefer it.',
    status: 'planned',
    path: '/typescript/as-const',
  },
  {
    id: 'module-augmentation',
    title: 'Module Augmentation',
    topic: 'typescript',
    description: 'Extending third-party types (e.g. adding custom props to a library component).',
    interviewNotes: 'Practical skill for typing CSS Modules, env vars, or extending vendor types.',
    status: 'planned',
    path: '/typescript/module-augmentation',
  },

  // --- React 19 ---
  {
    id: 'actions-use-action-state',
    title: 'Actions & useActionState',
    topic: 'react-19',
    description: 'Form submission with pending state and returned errors, without manual useState wiring.',
    interviewNotes: 'Newest way to answer "how do you handle form submission state" questions.',
    status: 'planned',
    path: '/react-19/actions-use-action-state',
  },
  {
    id: 'use-optimistic',
    title: 'useOptimistic',
    topic: 'react-19',
    description: 'Showing an optimistic UI update while a mutation is still in flight.',
    interviewNotes: 'Ties directly into the "optimistic updates" data-fetching topic below.',
    status: 'planned',
    path: '/react-19/use-optimistic',
  },
  {
    id: 'use-hook',
    title: 'The use() Hook',
    topic: 'react-19',
    description: 'Reading a promise or context conditionally, inside render.',
    interviewNotes: 'Distinguishes candidates who kept up with React 19 vs stuck on 18 patterns.',
    status: 'planned',
    path: '/react-19/use-hook',
  },
  {
    id: 'ref-as-prop',
    title: 'ref as a Prop',
    topic: 'react-19',
    description: 'Passing `ref` directly to function components without `forwardRef`.',
    interviewNotes: 'Simplifies a very commonly-asked-about pattern (imperative handles, focus management).',
    status: 'planned',
    path: '/react-19/ref-as-prop',
  },
  {
    id: 'document-metadata',
    title: 'Document Metadata',
    topic: 'react-19',
    description: 'Rendering `<title>`/`<meta>` directly from components, hoisted to `<head>` automatically.',
    interviewNotes: 'Replaces the need for react-helmet in many SPAs — worth knowing it exists.',
    status: 'planned',
    path: '/react-19/document-metadata',
  },
  {
    id: 'server-components-overview',
    title: 'Server Components (conceptual)',
    topic: 'react-19',
    description: 'Read-only overview: what RSC changes about data fetching/bundling. Not runnable in this Vite SPA.',
    interviewNotes: 'Frequently asked conceptually even on non-Next.js teams — know the mental model.',
    status: 'planned',
    path: '/react-19/server-components-overview',
  },

  // --- Hooks ---
  {
    id: 'use-reducer',
    title: 'useReducer',
    topic: 'hooks',
    description: 'Managing complex local state transitions with a reducer instead of many useState calls.',
    interviewNotes: 'Tests when useState stops scaling, and how reducers relate to Redux.',
    status: 'planned',
    path: '/hooks/use-reducer',
  },
  {
    id: 'use-memo-use-callback',
    title: 'useMemo / useCallback',
    topic: 'hooks',
    description: 'Memoizing expensive computations and stable function identities, and when it actually helps.',
    interviewNotes: 'One of the most-asked "when would you NOT use this" performance questions.',
    status: 'planned',
    path: '/hooks/use-memo-use-callback',
  },
  {
    id: 'use-ref',
    title: 'useRef',
    topic: 'hooks',
    description: 'DOM node access plus mutable values that persist without triggering re-renders.',
    interviewNotes: 'Checks understanding of the render vs mutation distinction.',
    status: 'planned',
    path: '/hooks/use-ref',
  },
  {
    id: 'custom-hooks',
    title: 'Custom Hooks',
    topic: 'hooks',
    description: 'Extracting reusable stateful logic (e.g. useDebounce, useToggle) from components.',
    interviewNotes: 'Almost every senior interview includes "build a custom hook for X".',
    status: 'planned',
    path: '/hooks/custom-hooks',
  },
  {
    id: 'use-imperative-handle',
    title: 'useImperativeHandle',
    topic: 'hooks',
    description: 'Exposing a controlled imperative API (e.g. focus(), reset()) from a child to a parent ref.',
    interviewNotes: 'Comes up with custom form controls / video players / modal dialogs.',
    status: 'planned',
    path: '/hooks/use-imperative-handle',
  },
  {
    id: 'use-layout-effect-vs-use-effect',
    title: 'useLayoutEffect vs useEffect',
    topic: 'hooks',
    description: 'Timing differences and when a synchronous DOM read/write before paint matters.',
    interviewNotes: 'Classic "explain the difference" question that trips up mid-level candidates.',
    status: 'planned',
    path: '/hooks/use-layout-effect-vs-use-effect',
  },
  {
    id: 'use-transition-use-deferred-value',
    title: 'useTransition / useDeferredValue',
    topic: 'hooks',
    description: 'Marking updates as non-urgent to keep typing/interactions responsive under load.',
    interviewNotes: 'Concurrent React feature interviewers use to probe for React 18+ knowledge.',
    status: 'planned',
    path: '/hooks/use-transition-use-deferred-value',
  },
  {
    id: 'use-sync-external-store',
    title: 'useSyncExternalStore',
    topic: 'hooks',
    description: 'Subscribing to external (non-React) state sources safely under concurrent rendering.',
    interviewNotes: "What libraries like Zustand/Redux use under the hood — good \"how does X work\" answer.",
    status: 'planned',
    path: '/hooks/use-sync-external-store',
  },
  {
    id: 'use-id',
    title: 'useId',
    topic: 'hooks',
    description: 'Generating stable, unique IDs for accessible label/input pairing across server and client.',
    interviewNotes: 'Small but real a11y-adjacent hook, easy to forget exists.',
    status: 'planned',
    path: '/hooks/use-id',
  },

  // --- Component Patterns ---
  {
    id: 'compound-components',
    title: 'Compound Components',
    topic: 'component-patterns',
    description: 'A parent + implicit-context children API, e.g. <Tabs><Tabs.Tab/></Tabs>.',
    interviewNotes: 'Common design-a-component-API interview exercise (build your own <Select>).',
    status: 'planned',
    path: '/component-patterns/compound-components',
  },
  {
    id: 'render-props',
    title: 'Render Props',
    topic: 'component-patterns',
    description: 'Sharing behavior by passing a function as a child/prop that returns JSX.',
    interviewNotes: 'Older but still-asked pattern; useful contrast against hooks-based reuse.',
    status: 'planned',
    path: '/component-patterns/render-props',
  },
  {
    id: 'controlled-uncontrolled',
    title: 'Controlled vs Uncontrolled',
    topic: 'component-patterns',
    description: 'Same input built two ways: state-driven value vs ref-read DOM value.',
    interviewNotes: 'Extremely common form-related interview question, also ties into react-hook-form.',
    status: 'planned',
    path: '/component-patterns/controlled-uncontrolled',
  },
  {
    id: 'headless-components',
    title: 'Headless Components',
    topic: 'component-patterns',
    description: 'Logic-only components/hooks that render nothing themselves, consumers supply the UI.',
    interviewNotes: "Explains how libraries like Radix/Headless UI/react-table are built.",
    status: 'planned',
    path: '/component-patterns/headless-components',
  },
  {
    id: 'slot-children-composition',
    title: 'Slot / Children Composition',
    topic: 'component-patterns',
    description: 'Using `children`/named slot props instead of config props to compose layout.',
    interviewNotes: '"How do you avoid prop-drilling config into a layout component" answer.',
    status: 'planned',
    path: '/component-patterns/slot-children-composition',
  },
  {
    id: 'polymorphic-components',
    title: 'Polymorphic Components (as prop)',
    topic: 'component-patterns',
    description: 'A component that renders as a different element/tag via an `as` prop, fully typed.',
    interviewNotes: 'Advanced TS + component design combo, ties back to generics.',
    status: 'planned',
    path: '/component-patterns/polymorphic-components',
  },
  {
    id: 'hocs',
    title: 'Higher-Order Components',
    topic: 'component-patterns',
    description: 'A function that wraps a component to inject props or behavior (e.g. withAuth).',
    interviewNotes: 'Legacy but still referenced pattern; good to compare against hooks.',
    status: 'planned',
    path: '/component-patterns/hocs',
  },

  // --- State Management ---
  {
    id: 'context-api',
    title: 'Context API',
    topic: 'state-management',
    description: 'Sharing state across a subtree without prop drilling, and its re-render pitfalls.',
    interviewNotes: 'Baseline every React interview expects; also sets up the comparison below.',
    status: 'planned',
    path: '/state-management/context-api',
  },
  {
    id: 'zustand',
    title: 'Zustand',
    topic: 'state-management',
    description: 'Minimal external store with selector-based subscriptions, no boilerplate.',
    interviewNotes: 'Increasingly the "lightweight Redux alternative" teams ask about.',
    status: 'planned',
    path: '/state-management/zustand',
  },
  {
    id: 'redux-toolkit',
    title: 'Redux Toolkit',
    topic: 'state-management',
    description: 'Slices, createSlice, and the modern, boilerplate-light way to write Redux.',
    interviewNotes: 'Still the most-referenced state library in job postings; RTK is the modern baseline.',
    status: 'planned',
    path: '/state-management/redux-toolkit',
  },
  {
    id: 'state-management-comparison',
    title: 'Context vs Zustand vs Redux Toolkit',
    topic: 'state-management',
    description: 'Same small app (e.g. a cart) implemented three ways, compared side by side.',
    interviewNotes: 'Directly answers the "how do you choose a state management approach" discussion question.',
    status: 'planned',
    path: '/state-management/comparison',
  },
  {
    id: 'derived-state-selectors',
    title: 'Derived State & Selectors',
    topic: 'state-management',
    description: 'Computing values from state instead of storing them, and memoized selector patterns.',
    interviewNotes: '"Why is your state out of sync" bugs usually trace back to skipping this.',
    status: 'planned',
    path: '/state-management/derived-state-selectors',
  },

  // --- Data Fetching ---
  {
    id: 'tanstack-query-basics',
    title: 'TanStack Query Basics',
    topic: 'data-fetching',
    description: 'Declarative fetching with automatic loading/error state and background refetching.',
    interviewNotes: 'The current industry-standard answer to "how do you handle server state".',
    status: 'planned',
    path: '/data-fetching/tanstack-query-basics',
  },
  {
    id: 'caching-invalidation',
    title: 'Caching & Invalidation',
    topic: 'data-fetching',
    description: 'Query keys, staleTime/gcTime, and invalidating queries after a mutation.',
    interviewNotes: 'Where most real-world data-fetching bugs and interview follow-ups live.',
    status: 'planned',
    path: '/data-fetching/caching-invalidation',
  },
  {
    id: 'optimistic-updates',
    title: 'Optimistic Updates',
    topic: 'data-fetching',
    description: 'Updating the UI before the server confirms, with rollback on failure.',
    interviewNotes: 'Common "how would you make this feel instant" system-design-ish question.',
    status: 'planned',
    path: '/data-fetching/optimistic-updates',
  },
  {
    id: 'pagination-infinite-queries',
    title: 'Pagination & Infinite Queries',
    topic: 'data-fetching',
    description: 'Page-based and cursor-based fetching, plus infinite-scroll loading.',
    interviewNotes: 'Practical, very frequently built in take-home assignments.',
    status: 'planned',
    path: '/data-fetching/pagination-infinite-queries',
  },
  {
    id: 'suspense-data-fetching',
    title: 'Suspense-Integrated Fetching',
    topic: 'data-fetching',
    description: 'Using `useSuspenseQuery` so loading states are handled by a Suspense boundary.',
    interviewNotes: 'Ties data-fetching directly into the Error Handling / Suspense topic below.',
    status: 'planned',
    path: '/data-fetching/suspense-data-fetching',
  },

  // --- Forms ---
  {
    id: 'react-hook-form-basics',
    title: 'react-hook-form Basics',
    topic: 'forms',
    description: 'Uncontrolled-by-default form state with register/handleSubmit and minimal re-renders.',
    interviewNotes: 'The most commonly used form library in current job listings.',
    status: 'planned',
    path: '/forms/react-hook-form-basics',
  },
  {
    id: 'zod-validation',
    title: 'Zod Schema Validation',
    topic: 'forms',
    description: 'Defining a validation schema once and deriving both types and runtime checks from it.',
    interviewNotes: '"How do you keep validation and TS types in sync" is a very common question.',
    status: 'planned',
    path: '/forms/zod-validation',
  },
  {
    id: 'controlled-vs-uncontrolled-inputs',
    title: 'Controlled vs Uncontrolled Inputs (in forms)',
    topic: 'forms',
    description: 'When RHF still needs a Controller wrapper (e.g. for custom/library inputs).',
    interviewNotes: 'Follow-up to the component-patterns version, applied to a real form library.',
    status: 'planned',
    path: '/forms/controlled-vs-uncontrolled-inputs',
  },
  {
    id: 'dynamic-field-arrays',
    title: 'Dynamic Field Arrays',
    topic: 'forms',
    description: 'Add/remove/reorder repeating form sections with useFieldArray.',
    interviewNotes: 'Common take-home task: "build a form where users can add multiple X".',
    status: 'planned',
    path: '/forms/dynamic-field-arrays',
  },

  // --- Routing ---
  {
    id: 'nested-routes',
    title: 'Nested Routes',
    topic: 'routing',
    description: 'Layout routes with `<Outlet/>` rendering matched child routes.',
    interviewNotes: 'This scaffold already uses the pattern — this demo makes it explicit and interactive.',
    status: 'planned',
    path: '/routing/nested-routes',
  },
  {
    id: 'dynamic-params',
    title: 'Dynamic Route Params',
    topic: 'routing',
    description: 'Reading `:id`-style segments and query params with useParams/useSearchParams.',
    interviewNotes: 'Needed for virtually any list/detail-page interview task.',
    status: 'planned',
    path: '/routing/dynamic-params',
  },
  {
    id: 'loaders-actions',
    title: 'Loaders & Actions',
    topic: 'routing',
    description: 'Fetching data before a route renders, and handling form submissions via route actions.',
    interviewNotes: "React Router's answer to server-state-on-navigation — good to contrast with TanStack Query.",
    status: 'planned',
    path: '/routing/loaders-actions',
  },
  {
    id: 'protected-routes',
    title: 'Protected Routes',
    topic: 'routing',
    description: 'Redirecting unauthenticated users away from a route, and back after login.',
    interviewNotes: 'Nearly every real app needs this; frequently asked as a design question.',
    status: 'planned',
    path: '/routing/protected-routes',
  },
  {
    id: 'route-based-code-splitting',
    title: 'Route-Based Code Splitting',
    topic: 'routing',
    description: 'Lazy-loading route components so each route ships its own JS chunk.',
    interviewNotes: 'Directly connects routing to the Performance topic below.',
    status: 'planned',
    path: '/routing/route-based-code-splitting',
  },

  // --- Performance ---
  {
    id: 'react-memo',
    title: 'React.memo',
    topic: 'performance',
    description: 'Skipping re-renders of a component when its props are shallow-equal.',
    interviewNotes: '"When does memo NOT help" is the real question behind this one.',
    status: 'planned',
    path: '/performance/react-memo',
  },
  {
    id: 'memoization-deep-dive',
    title: 'useMemo/useCallback Deep Dive',
    topic: 'performance',
    description: 'Measuring before/after with React DevTools Profiler to prove memoization actually helped.',
    interviewNotes: 'Separates candidates who measure from candidates who memoize everything by reflex.',
    status: 'planned',
    path: '/performance/memoization-deep-dive',
  },
  {
    id: 'code-splitting-lazy',
    title: 'Code Splitting & React.lazy',
    topic: 'performance',
    description: 'Splitting a heavy component into its own chunk, loaded on demand behind Suspense.',
    interviewNotes: 'Standard bundle-size-reduction answer in performance interview questions.',
    status: 'planned',
    path: '/performance/code-splitting-lazy',
  },
  {
    id: 'list-virtualization',
    title: 'List Virtualization',
    topic: 'performance',
    description: 'Rendering only visible rows of a long list, e.g. with react-window.',
    interviewNotes: '"How would you render 10,000 rows" is an extremely common performance prompt.',
    status: 'planned',
    path: '/performance/list-virtualization',
  },
  {
    id: 'profiling-react-devtools',
    title: 'Profiling with React DevTools',
    topic: 'performance',
    description: 'Reading flamegraphs to find which component re-rendered and why.',
    interviewNotes: 'Practical skill interviewers sometimes ask you to demonstrate live.',
    status: 'planned',
    path: '/performance/profiling-react-devtools',
  },
  {
    id: 'react-compiler-vs-manual-memoization',
    title: 'React Compiler vs Manual Memoization',
    topic: 'performance',
    description: 'Toggling the React Compiler on this exact sandbox and comparing generated behavior.',
    interviewNotes: 'A forward-looking topic; shows awareness of where the ecosystem is heading.',
    status: 'planned',
    path: '/performance/react-compiler-vs-manual-memoization',
  },

  // --- Error Handling ---
  {
    id: 'error-boundaries',
    title: 'Error Boundaries',
    topic: 'error-handling',
    description: 'Catching render-time errors in a subtree and showing a fallback UI instead of a blank screen.',
    interviewNotes: '"What does try/catch NOT catch in React" is the classic lead-in question.',
    status: 'planned',
    path: '/error-handling/error-boundaries',
  },
  {
    id: 'suspense-for-data',
    title: 'Suspense for Data',
    topic: 'error-handling',
    description: 'Using Suspense boundaries to show fallback UI while data-fetching promises resolve.',
    interviewNotes: 'Bridges Error Handling and Data Fetching topics — commonly asked together.',
    status: 'planned',
    path: '/error-handling/suspense-for-data',
  },
  {
    id: 'granular-vs-global-boundaries',
    title: 'Granular vs Global Boundaries',
    topic: 'error-handling',
    description: 'Placing boundaries per-widget vs per-page/app, and the UX tradeoffs of each.',
    interviewNotes: 'Real architecture decision — "would you put one boundary or many" comes up often.',
    status: 'planned',
    path: '/error-handling/granular-vs-global-boundaries',
  },
  {
    id: 'retry-fallback-ux',
    title: 'Retry & Fallback UX',
    topic: 'error-handling',
    description: 'Giving a failed boundary/query a "try again" action instead of a dead end.',
    interviewNotes: 'The follow-up question after "how do you handle errors": "...and then what?"',
    status: 'planned',
    path: '/error-handling/retry-fallback-ux',
  },

  // --- Testing ---
  {
    id: 'rtl-basics',
    title: 'RTL Basics',
    topic: 'testing',
    description: 'render/screen/userEvent, and querying by role/text the way a user would.',
    interviewNotes: 'Baseline expectation for any team that writes component tests.',
    status: 'planned',
    path: '/testing/rtl-basics',
  },
  {
    id: 'mocking-network-modules',
    title: 'Mocking Network & Modules',
    topic: 'testing',
    description: 'Intercepting requests with MSW, and mocking modules/timers with Vitest.',
    interviewNotes: '"How do you test a component that fetches data" is a near-universal ask.',
    status: 'planned',
    path: '/testing/mocking-network-modules',
  },
  {
    id: 'testing-custom-hooks',
    title: 'Testing Custom Hooks',
    topic: 'testing',
    description: 'Using renderHook to test hook logic in isolation from any component.',
    interviewNotes: 'Follow-up once you have custom hooks — "how would you unit test just the hook".',
    status: 'planned',
    path: '/testing/testing-custom-hooks',
  },
  {
    id: 'testing-async-forms',
    title: 'Testing Async Flows & Forms',
    topic: 'testing',
    description: 'Awaiting findBy* queries and simulating multi-step form submission with validation errors.',
    interviewNotes: 'Where most flaky-test interview war-stories come from — good to practice deliberately.',
    status: 'planned',
    path: '/testing/testing-async-forms',
  },

  // --- Accessibility ---
  {
    id: 'semantic-html',
    title: 'Semantic HTML',
    topic: 'accessibility',
    description: 'Choosing the right element (button vs div, nav, landmark regions) before reaching for ARIA.',
    interviewNotes: '"Why not just use a div with onClick" is a very common a11y interview question.',
    status: 'planned',
    path: '/accessibility/semantic-html',
  },
  {
    id: 'aria-roles-labels',
    title: 'ARIA Roles & Labels',
    topic: 'accessibility',
    description: 'Adding roles/labels only where semantic HTML falls short (custom widgets).',
    interviewNotes: 'Tests whether you know ARIA is a last resort, not a first reach.',
    status: 'planned',
    path: '/accessibility/aria-roles-labels',
  },
  {
    id: 'focus-management',
    title: 'Focus Management',
    topic: 'accessibility',
    description: 'Moving focus correctly when opening a modal, after a route change, or on error.',
    interviewNotes: 'Practical skill that most "build a modal" take-homes silently grade you on.',
    status: 'planned',
    path: '/accessibility/focus-management',
  },
  {
    id: 'keyboard-navigation',
    title: 'Keyboard Navigation',
    topic: 'accessibility',
    description: 'Full keyboard operability for a custom widget (tabs, menus, dialogs) without a mouse.',
    interviewNotes: '"Can you use this with just a keyboard" is a real, easy live-demo interview check.',
    status: 'planned',
    path: '/accessibility/keyboard-navigation',
  },
  {
    id: 'accessible-forms',
    title: 'Accessible Forms',
    topic: 'accessibility',
    description: 'Label association, error announcement (aria-live), and describing fields with aria-describedby.',
    interviewNotes: 'Combines the Forms and Accessibility topics — a common real-world requirement.',
    status: 'planned',
    path: '/accessibility/accessible-forms',
  },
  {
    id: 'color-contrast-basics',
    title: 'Color Contrast Basics',
    topic: 'accessibility',
    description: 'Checking text/background contrast ratios against WCAG AA using this app\'s own theme tokens.',
    interviewNotes: 'Shows a11y awareness extends beyond markup into visual design decisions.',
    status: 'planned',
    path: '/accessibility/color-contrast-basics',
  },
];
